# Generated by Django 3.1.4 on 2020-12-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201214_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
